// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6i9EYhPmT9W0-aiZFX8VWozg50gK7rgA',
    appId: '1:265331366092:web:477311e9204234f0e2ca69',
    messagingSenderId: '265331366092',
    projectId: 'bank-sampah-e2894',
    authDomain: 'bank-sampah-e2894.firebaseapp.com',
    storageBucket: 'bank-sampah-e2894.appspot.com',
    measurementId: 'G-9YXPRDRGRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaBX_w_49jCshvRcALqOLfEVtT5pQ7mY',
    appId: '1:265331366092:android:acad261995fc0452e2ca69',
    messagingSenderId: '265331366092',
    projectId: 'bank-sampah-e2894',
    storageBucket: 'bank-sampah-e2894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUX7cmOb72qX8zhPuYDBy8kQB4sdiXOMU',
    appId: '1:265331366092:ios:bc272a059197115ee2ca69',
    messagingSenderId: '265331366092',
    projectId: 'bank-sampah-e2894',
    storageBucket: 'bank-sampah-e2894.appspot.com',
    iosClientId: '265331366092-hmpm63j45l1a1p1hin98jjmdsn0eqb8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniProjectBankSampah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUX7cmOb72qX8zhPuYDBy8kQB4sdiXOMU',
    appId: '1:265331366092:ios:bc272a059197115ee2ca69',
    messagingSenderId: '265331366092',
    projectId: 'bank-sampah-e2894',
    storageBucket: 'bank-sampah-e2894.appspot.com',
    iosClientId: '265331366092-hmpm63j45l1a1p1hin98jjmdsn0eqb8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniProjectBankSampah',
  );
}
